# yaml used instead of json due to ease and ability to comment <3

# bot requires a restart after updating config
# bot messages can be updated in the json files in this directory
# if some parts are missing, the bot will not work

bot:
    options:
        cooldown: 1440  # enter time in minutes (will only work if database is sqlite or mysql)
        queueLimit: 20  # max players in queue, dont go above something like 40 or the bot cant send a message
        testerLimit: 5  # max number of testers per region
        reloadQueue: 10 # time in seconds on how frequently you want to reload the queue, reccomended to stay above 15

    messages:           # messages to send
        noPermission: You do not have the permission to use this command.       # message to send if a user doesnt have permission to execute a command
        notTicketCatagory: Command can only be ran inside of testing channels   # message to send if a user tries running /result in a non ticket catagory
        resultMessageSent: Result message sent!                                 # message to send as an ephemeral after a user sucessfully runs /results
        error: An error as occured                                              # message to send if the bot has an error
        addToQueue: You have been added to queue!                               # message to send when a user is added to a queue
        testerOpenQueue: "You have opened the queue!"                           # message to send when a tester opens a queue
        alreadyInQueue: "You are already in the queue!"                         # message to send if a user is already in a queue
        queueFull: "The queue is full!"                                         # message to send if the queue is full
        notInQueue: "You are not in the queue!"                                 # message to send if a user is not in a queue when they try to leave
        leaveQueue: "You have left the queue!"                                  # message to send when a user leaves the queue

    channels:   # the format is channel: channel_id
        results: 1487509121573064764        # post results
        enterWaitlist: 1487509169681727609  # where users join a channel for a queue

    catagories:
        highTests: 1487509632602738870    # Catagory where users with a high tiers ticket will go

    roles:      # the format is role: role_id
        tester: 1487509818238439486

    tiers:      # the format is tier: role_id
        lt5: 1487509970634276894
        ht5: 1487510054042210335
        lt4: 1487510127144730818
        ht4: 1487510217402093679
        lt3: 1487510277569380524
        ht3: 1487510340521427094
        lt2: 1487510459803373749
        ht2: 1487510519983247531
        lt1: 1487510580943130634
        ht1: 1487510636257607884

    highTiers:  # tiers you want to create a seperate ticket for
        - ht1
        - lt1
        - ht2
        - lt2
        - ht3

    regions:    # you can always add more regions
        EU: 
            queue_channel: 1487511920864137366      # channel for queue to be posted in
            ticket_catagory: 1487510804939931939    # catagory for tests to go in
            role_ping: 1487511223422681098    # role to ping when queue is open
        NA:    
            queue_channel: 1487511933727936643
            ticket_catagory: 1487510828902256811
            role_ping: 1487511246868844644
        OCE:
            queue_channel: 1487518258922914074
            ticket_catagory: 1487518394449133709
            role_ping: 1487518474518532147
        Asia:
            queue_channel: 1487569265308733501
            ticket_catagory: 1487538138686685264
            role_ping: 1487538017492013177
database:
    # options are "mysql", "sqlite", only use mysql if you know what you are doing, if you switch, data will not transfer, you will need to write your own script to transfer the data
    type: sqlite 

    mysql:      # only use this if you know what you are doing
        host: localhost
        port: 3306
        user: root
        password: root
        database: tiers # must be created before starting bot

# UwU